### ISSUE TITLE
deep_merge with standard mappings?

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_import#10]
Without reading the documentation on standard mappings, one would _assume_ standard mappings were deep merged, so that field mappings are merged with the standard mapping field mappings rather than replacing them.

Should we therefore make this change? It would be non-breaking with mappings that currently need to redefine the standard mappings field mapping(s) so they remain.

**Comment by joshpencheon** [comment]
(See #1 for discussion on mutating standard mappings.)

**Comment by timgentry** [comment]
We should not mutate standard_mappings, is reverse_merge deep?

**Comment by joshpencheon** [comment]
The general approach taken for the "deep clone" previously was to do a roundtrip through some serialisation format, e.g.

```ruby
clone = YAML.load(YAML.dump(original))
```

Or it might be possible to use `Marshal` in a similar way.

I'm not aware of an out-of-the-box way of merging together richer structures.

**Comment by timgentry** [comment]
I _guess_ `Marshal` is faster? Given the clearly defined structure of a column mapping I think we'd have to roll our own merge function.

**Comment by timgentry** [comment]
```ruby
require 'benchmark'
require 'yaml'

n = 50_000
original = YAML.load <<-YML
  - column: surname
    rawtext_name: surname
    mappings:
    - field: surname
      clean: :name
  - column: forename
    rawtext_name: forenames
    mappings:
    - field: forenames
      clean: :name
  - column: sex
    rawtext_name: sex
    mappings:
    - field: sex
      clean: :sex
  - column: nhs_no
    rawtext_name: nhsnumber
    mappings:
    - field: nhsnumber
      clean: :nhsnumber
YML

Benchmark.bm do |x|
  x.report("Marshal:") do
    n.times { Marshal.load(Marshal.dump(original)) }
  end
  x.report("YAML:") do
    n.times { YAML.load(YAML.dump(original)) }
  end
end
```

```
       user     system      total        real
Marshal:  2.450000   0.020000   2.470000 (  2.561565)
YAML: 37.170000   0.160000  37.330000 ( 37.833326)
```

**Comment by joshpencheon** [comment]
@timgentry do you think there is more to work on here? I'm conscious that as of 582ce42b (and indeed, prior to it), additional `mappings` supplied alongside a `standard_mapping` are merged in, rather than replacing any `mappings` that the `standard_mapping` predefines. All other properties are replaced.

**Comment by timgentry** [comment]
I think it is now a non-issue, we can always reopen it if necessary.
