### ISSUE TITLE
Major version bump changes

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_import#11]
With the impending major version bump, is it worth taking the opportunity to move the legacy file helpers lib/ndr_import/helpers/file/*.rb out into a new legacy helpers gem?

**Comment by joshpencheon** [comment]
Unless they're a hindrance to development of `ndr_import`, I'm not sure it's worth the effort?

I've no objection to them being deprecated and then stagnating; AFAIK, there's no requirement to remove deprecated code whilst following SemVer.

**Comment by timgentry** [comment]
There isn't that I'm aware of, but seeing as all our new systems don't use them, I wondered if it was worth a quick lift and shift while making a major version bump (rather than having another one at a later date)
