### ISSUE TITLE
Automatically generating a per row identifier

### ISSUE THREAD

**Issue by timgentry** [PublicHealthEngland/ndr_import#33]
**As a** developer
**I want to** declare that I want a per row identifier generated by the mapper
**So that** I can identify all the mapped record instances generated by the same row.

Acceptance criteria:
`table = NdrImport::Table.new(..., row_identifier: :uuid, columns: [...])` should add a `row_identifier` field to the mapped fields, with the same UUID for all records originating from the same row.

**Comment by suezhou** [comment]
The feature now included in v8.2.0
