### ISSUE TITLE
Add array functionality to mapper

### ISSUE THREAD

**Issue by ollietulloch** [PublicHealthEngland/ndr_import#4]
Add functionality to `NdrImport::Mapper#mapped_line` which allows multiple incoming columns to be appended into a single field as an array.

**Comment by timgentry** [comment]
Could this be achieved by simply omitting the join instruction to ordered field concatenation?

**Comment by joshpencheon** [comment]
I believe so, although I think the `:compact` option would also cease to function as things currently stand.

**Comment by joshpencheon** [comment]
@ollietulloch is this still a relevant request? Please close if not.

**Comment by ollietulloch** [comment]
This hasn’t been required since opening this issue ~2 years ago so happy to close. I’ll open a new issue if this functionality is required at a later date.
